# Generated by Django 5.0.6 on 2024-11-16 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('C', 'Cardio machine'), ('R', 'Resistance machine'), ('F', 'Free weights'), ('O', 'Other')], default='C', max_length=1)),
                ('weight_measured', models.BooleanField(default=False, verbose_name='Is this exercise measured by weight?')),
                ('reps_measured', models.BooleanField(default=False, verbose_name='Is this exercise measured by number of repetitions?')),
                ('duration_measured', models.BooleanField(default=False, verbose_name='Is this exercise measured by its duration?')),
                ('distance_measured', models.BooleanField(default=False, verbose_name='Is this exercise measured by distance?')),
                ('difficulty_level_measured', models.BooleanField(default=False, verbose_name='Is this exercise measured by difficulty level?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight kg)')),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=1)),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight (kgs)')),
                ('reps', models.IntegerField(blank=True, null=True, verbose_name='Repetitions')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Distance (metres)')),
                ('difficulty_level', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouttracker.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouttracker.workout')),
            ],
            options={
                'ordering': ['workout__start_dt', 'exercise__category', 'exercise__name'],
            },
        ),
    ]
