# Generated by Django 5.0.6 on 2024-11-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['id']},
        ),
    ]
